### ISSUE TITLE
German Mapping

### ISSUE THREAD

**Issue by tiagomartinho** [b123400/BRLocaleMap#1] opened 2018-12-01 07:55 UTC
I noticed a bug where German is mapped incorrectly to "de_DE" instead of "de" using the Google Service, this causes Xliffie to fail with the 400 HTTP Error when using the translation API

**Comment by b123400** [comment] 2018-12-05 06:12
Thank you for the report! I am quite busy now but will fix it (and release a new version of Xliffie) as soon as possible

**Comment by b123400** [comment] 2018-12-09 10:10
@tiagomartinho I couldn't reproduce the issue, `de_DE` is nowhere to be found in the repositories. I wonder what is your source and target languages, and how is the Xliff file generated? It will be very helpful if you can share a Xliff file that triggers the bug. Thank you!

**Comment by b123400** [comment] 2018-12-10 06:27
OK, I've found the problem! Thx anyway :)

**Comment by b123400** [comment] 2018-12-12 07:46
Fixed with 1.5.0, available on App Store now

**Closed as completed by b123400** 2018-12-12 07:46 UTC
